name: "Component Builder Publish"
on:
  push:
    paths:
      - 'containers/fedora/**'
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  guest-fedora-amd64:
    runs-on: ubuntu-latest
    env:
      FEDORA_IMAGE: Fedora-Cloud-Base-Generic-41-1.4.x86_64.qcow2
      FEDORA_VERSION: 41
      CPU_ARCH: amd64
      FULL_EMULATION: "true"
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install dependencies for VM build
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qemu-system-x86 \
            libvirt-daemon-system \
            virtinst cloud-image-utils \
            libguestfs-tools
      - name: Tweak hosted runner to enable 'virt-sysprep'
        # https://bugs.launchpad.net/ubuntu/+source/linux/+bug/759725
        run: sudo chmod 0644 /boot/vmlinuz*
      - name: Fetch base Fedora image
        working-directory: ./containers/fedora
        run: wget -q "https://download.fedoraproject.org/pub/fedora/linux/releases/41/Cloud/x86_64/images/${{ env.FEDORA_IMAGE }}"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.21"
      - name: Create VM
        working-directory: ./containers/fedora
        env:
          PYTHONPATH: ${{ github.workspace }}
          ORGANIZATION_ID: ${{ secrets.BITWARDEN_ORGANIZATION_ID }}
          ACCESS_TOKEN: ${{ secrets.BITWARDEN_ACCESS_TOKEN }}
        run: ./build.sh
      - name: Logging to quay.io
        run: podman login -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_TOKEN }} quay.io
      - name: Tag & Push image to staging
        env:
          local_repository: "localhost/fedora"
          remote_repository: "quay.io/openshift-cnv/qe-cnv-tests-fedora-staging"
          arch_tag: "${{ env.FEDORA_VERSION }}-${{ env.CPU_ARCH }}"
          remote_tag: "${{ env.FEDORA_VERSION }}-dev"
        run: |
          podman tag "${local_repository}":"${arch_tag}" "${remote_repository}":"${arch_tag}"
          podman push "${remote_repository}":"${arch_tag}"
          podman manifest create --log-level=debug "${remote_repository}":"${remote_tag}" "${remote_repository}":"${arch_tag}"
          podman manifest push "${remote_repository}":"${remote_tag}" --all --format=v2s2
