name: Jira validation

on:
  push:


jobs:
  verify-jira:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add Config File to current folder
        run: |
          echo "$CONFIG_CONTENT" > jira.cfg
        env:
          CONFIG_CONTENT: ${{ secrets.JIRA_CONFIG }}

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install tox
        run: pip install tox

      - name: Run Tox with Environment Variables
        run: tox -e verify-bugs-are-open
